export default [
  {
    type: "constructor",
    inputs: [
      { name: "_eas", type: "address", internalType: "contract IEAS" },
      { name: "_delegatedOP", type: "address", internalType: "address" },
      { name: "_maxRanks", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "DEFAULT_ADMIN_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "attest",
    inputs: [
      {
        name: "attestation",
        type: "tuple",
        internalType: "struct Attestation",
        components: [
          { name: "uid", type: "bytes32", internalType: "bytes32" },
          { name: "schema", type: "bytes32", internalType: "bytes32" },
          { name: "time", type: "uint64", internalType: "uint64" },
          { name: "expirationTime", type: "uint64", internalType: "uint64" },
          { name: "revocationTime", type: "uint64", internalType: "uint64" },
          { name: "refUID", type: "bytes32", internalType: "bytes32" },
          { name: "recipient", type: "address", internalType: "address" },
          { name: "attester", type: "address", internalType: "address" },
          { name: "revocable", type: "bool", internalType: "bool" },
          { name: "data", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "attestationUIDs",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "delegatedOP",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "delegations",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "eas",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IEAS" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRank",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRankByDelegation",
    inputs: [{ name: "delegation", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRanks",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoleAdmin",
    inputs: [{ name: "role", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "grantRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "hasRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isPayable",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "maxRanks",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "multiAttest",
    inputs: [
      {
        name: "attestations",
        type: "tuple[]",
        internalType: "struct Attestation[]",
        components: [
          { name: "uid", type: "bytes32", internalType: "bytes32" },
          { name: "schema", type: "bytes32", internalType: "bytes32" },
          { name: "time", type: "uint64", internalType: "uint64" },
          { name: "expirationTime", type: "uint64", internalType: "uint64" },
          { name: "revocationTime", type: "uint64", internalType: "uint64" },
          { name: "refUID", type: "bytes32", internalType: "bytes32" },
          { name: "recipient", type: "address", internalType: "address" },
          { name: "attester", type: "address", internalType: "address" },
          { name: "revocable", type: "bool", internalType: "bool" },
          { name: "data", type: "bytes", internalType: "bytes" },
        ],
      },
      { name: "values", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "multiRevoke",
    inputs: [
      {
        name: "attestations",
        type: "tuple[]",
        internalType: "struct Attestation[]",
        components: [
          { name: "uid", type: "bytes32", internalType: "bytes32" },
          { name: "schema", type: "bytes32", internalType: "bytes32" },
          { name: "time", type: "uint64", internalType: "uint64" },
          { name: "expirationTime", type: "uint64", internalType: "uint64" },
          { name: "revocationTime", type: "uint64", internalType: "uint64" },
          { name: "refUID", type: "bytes32", internalType: "bytes32" },
          { name: "recipient", type: "address", internalType: "address" },
          { name: "attester", type: "address", internalType: "address" },
          { name: "revocable", type: "bool", internalType: "bool" },
          { name: "data", type: "bytes", internalType: "bytes" },
        ],
      },
      { name: "values", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "multicall",
    inputs: [{ name: "data", type: "bytes[]", internalType: "bytes[]" }],
    outputs: [{ name: "results", type: "bytes[]", internalType: "bytes[]" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "ranks",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revoke",
    inputs: [
      {
        name: "attestation",
        type: "tuple",
        internalType: "struct Attestation",
        components: [
          { name: "uid", type: "bytes32", internalType: "bytes32" },
          { name: "schema", type: "bytes32", internalType: "bytes32" },
          { name: "time", type: "uint64", internalType: "uint64" },
          { name: "expirationTime", type: "uint64", internalType: "uint64" },
          { name: "revocationTime", type: "uint64", internalType: "uint64" },
          { name: "refUID", type: "bytes32", internalType: "bytes32" },
          { name: "recipient", type: "address", internalType: "address" },
          { name: "attester", type: "address", internalType: "address" },
          { name: "revocable", type: "bool", internalType: "bool" },
          { name: "data", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "revokeRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "schemaId",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "updateRank",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      { name: "version", type: "uint8", indexed: false, internalType: "uint8" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RankUpdated",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "oldRank",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newRank",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "attestationUID",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleAdminChanged",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "previousAdminRole",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "newAdminRole",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleGranted",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleRevoked",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AccessDenied", inputs: [] },
  { type: "error", name: "InsufficientValue", inputs: [] },
  { type: "error", name: "InvalidEAS", inputs: [] },
  { type: "error", name: "InvalidLength", inputs: [] },
  { type: "error", name: "NotAuthorized", inputs: [] },
  { type: "error", name: "NotPayable", inputs: [] },
  { type: "error", name: "RankTooLow", inputs: [] },
] as const;
